### ISSUE TITLE
Install iTerm theme change script

### ISSUE THREAD

**Issue by IgorKrupenja** [IgorKrupenja/dotfiles#23]
Also needs proper install, need to use **download** here: https://iterm2.com/python-api/examples/theme.html

Issue link here https://gitlab.com/gnachman/iterm2/issues/6764#note_103467471

**Comment by krupenja** [comment]
Likely just curl the its file

**Comment by krupenja** [comment]
Alternatively, ask on SO how Python API scripts could be installed automatically

**Comment by krupenja** [comment]
or use git lfs https://git-lfs.github.com/

**Comment by igor-krupenja** [comment]
Also read https://iterm2.com/python-api/tutorial/running.html?highlight=run
